webtalk_init -webtalk_dir C:/Users/giaco/Documents/Uni/PoD/MaPD/MAPD_modA/15_uart/15_uart.sim/sim_1/behav/xsim/xsim.dir/tb_uart_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  7 18:17:59 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0614c21b-32fb-42cf-a511-937bb730607f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "dafda6d17aa545c8a11d0df942328fb7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6408_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3160895628 -regid "" -xml C:/Users/giaco/Documents/Uni/PoD/MaPD/MAPD_modA/15_uart/15_uart.sim/sim_1/behav/xsim/xsim.dir/tb_uart_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/giaco/Documents/Uni/PoD/MaPD/MAPD_modA/15_uart/15_uart.sim/sim_1/behav/xsim/xsim.dir/tb_uart_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/giaco/Documents/Uni/PoD/MaPD/MAPD_modA/15_uart/15_uart.sim/sim_1/behav/xsim/xsim.dir/tb_uart_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
