# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mapping.xdc

# IP: C:/Users/giaco/Documents/Uni/PoD/MaPD/vivado_proj/Pmod-I2S2-Arty-A7-35.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
